### ISSUE TITLE
Key vault screens seem to have moved on - error "The operation "List" is not enabled in this key vault's access policy.  "

### ISSUE THREAD

**Issue by tps99** [tayganr/purviewlab#46]
Looks like the Keyvault Portal screens have moved on and the dialogue for this section (Module 02B - Register & Scan (Azure SQL DB)) doesn't quite match the current portal

I ended up with the error above which I think I fixed using this fix (https://jd-bots.com/2021/07/27/fixed-the-operation-list-is-not-enabled-in-this-key-vaults-access-policy/) but not sure if that's the right approach

**Comment by tayganr** [comment]
Hi @tps99 , apologies in the delay to looking at this. I just re-ran through Module 2B and it appears to function as expected. 

Based on your error message ```The operation "List" is not enabled in this key vault's access policy. ```, I suspect the issue was because the Key Vault Access Policy assigned to the Azure Purview Managed identity was missing the **List** permission.

![image](https://user-images.githubusercontent.com/9876422/155604029-ae29781b-f109-4e19-a19d-d239ff1545f3.png)
